[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "TracerLL"
version = "0.1.14"
description = "TracerLL: High-performance embedded variable tracing library"
authors = [
    { name = "William Kers", email = "williamkers@integralmotions.com" },
    { name = "Jos Wigchert", email = "joswigchert@integralmotions.com" },
]
readme = "README.md"
dependencies = []
requires-python = ">=3.8"

[project.license]
text = "MIT"
files = ["LICENSE"]